# Generated by Django 5.0 on 2023-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_text',
            field=models.TextField(default='An explanation is needed for the answer here.'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default='An explanation is needed for the question here.'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(null=True, upload_to='uploads/user'),
        ),
    ]
