# Generated by Django 5.0 on 2023-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answers_answer_text_alter_questions_question_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='TimeLineItems',
            new_name='TimeLineItem',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
