# Generated by Django 5.0 on 2023-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_answers_answer_rename_lessons_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.TextField(default='An explanation is needed for the question here.'),
        ),
    ]
