# Generated by Django 5.0 on 2023-12-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='star_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
