# Generated by Django 5.0 on 2024-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_question_star_number_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
