# Generated by Django 5.0 on 2024-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='star_number',
            field=models.IntegerField(null=True),
        ),
    ]
