# Generated by Django 5.0 on 2024-01-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_lesson_lecturer_alter_lesson_lesson_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
